### ISSUE TITLE
CSS reset

### ISSUE THREAD

**Issue by moebiusmania** [casavo/habitat#18]
we need to introduce a CSS reset, but we are facing 2 options:

- adding it only to the Storybook and then each project that use Habitat should handle itself
- making it an exportable utility within Habitat

**Comment by YoannDelpierre** [comment]
Per curiosity, what kinf of reset do you need ?

**Comment by moebiusmania** [comment]
I'm adding an utility based on https://github.com/sindresorhus/modern-normalize and https://tailwindcss.com/docs/preflight (which itself uses `modern-normalize`)

**Comment by YoannDelpierre** [comment]
👍 

I think you should handle the reset by using `making it an exportable utility within Habitat`, like this you control everything on every projects.
