### ISSUE TITLE
post-merge branch delete

### ISSUE THREAD

**Issue by moebiusmania** [casavo/habitat#72]
at the moment when you aprrove a merge a PR the branch isnt deleted `automagically` as it happens in other projects, it would be nice to bring this feature here

**Comment by GiovanniVisentiniCasavo** [comment]
I think that this is the manual configuration: 
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches

but we can create a .settings file and use the `delete_branch_on_merge` see here: https://github.com/apps/settings

**Comment by moebiusmania** [comment]
done with #77
